### ISSUE TITLE
tslib error on webpack@5.0.0-rc.4

### ISSUE THREAD

**Issue by philcockfield** [module-federation/practical-module-federation#14]
I just submitted this as an [issue (#11613)](https://github.com/webpack/webpack/issues/11613) on the core webpack repo, then remembered you had an example using `rxjs` in the book, so head over to see if you had were doing something clever, but looks like the issue is real (not just me being a dummy):

![image](https://user-images.githubusercontent.com/185555/95529740-3810bf00-0a38-11eb-9d31-11894b632da0.png)

I have details written up in this reproduction repo: https://github.com/webpack/webpack/issues/11613

Thanks guys!

**Comment by jherr** [comment]
Looks to be fixed.
