### ISSUE TITLE
Chapter 9 code does not match book code at all

### ISSUE THREAD

**Issue by sethvoltz** [module-federation/practical-module-federation#6]
The code here for Chapter 9 is three modules: home, profile and search. There is no Header component as mentioned in the book. Additionally, none of the modules in Chapter 9 are using NPM fallback as the book chapter shows. 

The code Chapter 9 top-level `package.json` file is named `wp5-mfe-starter`.

**Comment by sethvoltz** [comment]
Chapters 10 and 11 also point to chapter9 here and book chapters 12 and 13 point to a non-existent chapter12 and chapter13 directories, respectively.

**Comment by jherr** [comment]
Yep, you are very right, sorry for not seeing these issues earlier. The code is now up to date and a new book release will be coming the week of 10/12/2020.
