### ISSUE TITLE
Book chapter 9 is cut off mid-sentence near the end

### ISSUE THREAD

**Issue by sethvoltz** [module-federation/practical-module-federation#7]
Both the ePub and PDF have the same bug:
![image](https://user-images.githubusercontent.com/39506/93819298-67d65f00-fc10-11ea-8d91-9217913e237b.png)

**Comment by sethvoltz** [comment]
There are also two Chapter 15s, FAQ and Troubleshooting.

**Comment by jherr** [comment]
Sorry about that, cleaned up in the next version which will be published soon.
